[pytest]
env =
    PLAYWRIGHT_TEST_ID_ATTRIBUTE=data-qa
addopts = --headed --slowmo 500

pythonpath = .
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*



markers =
    smoke: Смок
    slow: Медленные тесты
    regression: Запускает регресс тесты
    registration: Регистрация
    authorization: Тест авторизации